var STRING_ERROR_GENERICAJAX = 'There was an error processing your request, please try again.';

var WINDOWTYPE_BIDDING = 'biddingWindow';
var WINDOWTYPE_BIDDINGNOORDER = 'biddingNoOrderWindow';
var WINDOWTYPE_VIEWINTEREST = 'viewInterestWindow';
var WINDOWTYPE_VIEWINTERESTFIRM = 'viewInterestFirmWindow';
var WINDOWTYPE_VIEWINTERESTNOORDER = 'viewInterestNoOrderWindow';
var WINDOWTYPE_DEALCONFIRM = 'dealConfirmWindow';
var WINDOWTYPE_CHAT = 'chatWindow';
var WINDOWTYPE_DEALCOMPLETE = 'dealCompleteWindow';
var WINDOWTYPE_FILLORDERCONFIRM = 'fillOrderConfirmWindow';

var MEMBERSHIPTYPE_NOTSIGNEDUP = 0;
var MEMBERSHIPTYPE_BASIC = 1;
var MEMBERSHIPTYPE_ADVANCE = 2;
var MEMBERSHIPTYPE_MANAGER = 3;

var INTERESTTYPE_SELL = 1;
var INTERESTTYPE_BUY = 2;

var BIDTYPE_INDICATIVE = 1;
var BIDTYPE_FIRM = 2;
var BIDTYPE_REQUESTINDICATIVE = 3;
var BIDTYPE_REQUESTFIRM = 4;
var BIDTYPE_FILLORDER = 5;